Maven Dependencies to Render XML with Spring MVC ------------------------------------------------
	https://docs.spring.io/spring-boot/docs/2.4.5/reference/htmlsingle/

	* If you have the Jackson XML extension (jackson-dataformat-xml) on the classpath, you can use it to render XML responses.

		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>

	* If Jackson’s XML extension is not available and JAXB is available, XML can be rendered with the additional requirement of having your POJO class annotated with @XmlRootElement
		JAXB is only available out of the box with Java 8. If you’re using a more recent Java generation, add the following dependency to your project:

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
		</dependency>

	BUT ALL CONTROLLER UNIT TESTS START TO FAIL WHEN ADDING THE DEPENDENCY ON jackson-dateformat-xml

		java.lang.AssertionError: No value at JSON path "$.categories"

		at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:304)
		at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:73)
		at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$0(JsonPathResultMatchers.java:87)
		at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:196)
		at guru.springfamework.controller.v1.CategoryControllerTest.getAll(CategoryControllerTest.java:67)
		...
		at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
		Caused by: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['categories'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.
			at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)
			..
			at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:301)
			... 69 more

	ANSWER: As we previously had only one view, we didn't specify in our tests what media type to return and it is likely returning a '406 HTTP Not Acceptable' now.
			So specify the media type you will accept in all the failing mockMvc requests

			.accept(MediaType.APPLICATION_JSON)